AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - spec/*
    - config/**/*
    - Gemfile
    - spec/**/*
    - bin/*
Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false